# This is the final, correct configuration for Netlify.
[build]
  base    = "my_cointrak_react"
  # FIX: The publish directory is relative to the base directory.
  publish = "dist"
  command = "npm run build"
  
  [build.environment]
    NODE_VERSION = "20"
    VITE_API_URL = "https://cointrak-api.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200