# Blueprint for deploying the CoinTrak application on Render

services:
  # This is the Laravel API Web Service
  - type: web
    name: cointrak-api
    env: php      # <-- FIX: The correct key for PHP is 'env', not 'runtime'.
    plan: free
    rootDir: my_cointrak_api
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      # Automatically generate a secure application key.
      - key: APP_KEY
        generateValue: true
      # Connect to the database defined in the 'databases' block below.
      - key: DATABASE_URL
        fromDatabase:
          name: cointrak-db
          property: connectionString

# This is the PostgreSQL Database
databases:
  - name: cointrak-db
    plan: free