services:
  - type: web
    name: fiambond-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fiambond-db
          property: connectionString
      - key: PORT
        value: 10000
    # --- THIS IS THE FIX ---
    # We run the migrate command before starting the server.
    # The '&&' means "if the first command succeeds, then run the second".
    startCommand: php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=10000

databases:
  - name: fiambond-db
    plan: free