# Blueprint for deploying the CoinTrak application on Render

services:
  # This is the Laravel API Web Service
  - type: web
    name: cointrak-api
    runtime: php      # FIX: The correct key is 'runtime', not 'env'
    plan: free
    rootDir: my_cointrak_api
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      # Tell Render to generate a secure, random value for the APP_KEY.
      - key: APP_KEY
        generateValue: true
      # Connect to the database using the details from the 'databases' block.
      - key: DATABASE_URL
        fromDatabase:
          name: cointrak-db
          property: connectionString

# This is the PostgreSQL Database
databases:
  - name: cointrak-db
    plan: free