services:
  - type: web
    name: cointrak-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    # Add a health check to ensure the app starts correctly
    healthCheck:
      path: /api/health
      initialDelaySecs: 20
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cointrak-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: cointrak-db
    plan: free