services:
  - type: web
    name: cointrak-api
    env: php
    plan: free
    rootDir: my_cointrak_api
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cointrak-db
          property: connectionString

databases:
  - name: cointrak-db
    plan: free